rcar: scif: Fix BL31 linking
Upstream commit 78e61613738e ("Ensure BL31 does not print to boot
console by default") silently assumes that any platform console
driver used by BL31 provides the console_uninit() function.

It turns out this assumption is true for Renesas memory logging
driver [1] (masqueraded as a console driver). However, the
upstream expectation is broken by SCIF driver [2]. In other words,
if SCIF driver is compiled as part of BL31, BL31 linking will fail
with error message [3]. Fix this.

[1] plat/renesas/rcar/drivers/memdrv/rcar_console.S
[2] plat/renesas/rcar/drivers/scif/scif.S
[3] Build error avoided with this commit:
-----------------------------------------------------------
  LD      build/rcar/release/bl31/bl31.elf
..bl31/plat_common.o: In function `bl31_plat_runtime_setup':
plat_common.c: undefined reference to `console_uninit'
Makefile:600: recipe for target '.../bl31/bl31.elf' failed
make: *** [build/rcar/release/bl31/bl31.elf] Error 1
-----------------------------------------------------------

Signed-off-by: Eugeniu Rosca <erosca@de.adit-jv.com>